name: labels
on:
  push:
    paths:
      - .github/labels.json
      - .github/workflows/labels.yml
    branches:
      - main
  workflow_dispatch:
jobs:
  label:
    name: Manage GitHub labels
    runs-on: ubuntu-latest
    permissions: {}
      # contents: read
      # issues: write
      # pull-requests: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Manage labels
        uses: shogo82148/issue-label-manager-action@88cf24f2c942cdc308d2f15c23f5357c265b024f
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
